version: "3.9"

services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=goroot
      - POSTGRES_DB=goapidb
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
